name: curved_container
description: One Line Code for Curved Container.
version: 0.0.1
homepage: https://www.prabinjaishi.com.np/
repository:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true